// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "YetAnotherIVOD",
    platforms: [
        .iOS("17.0"),
        .macOS("14.0")
    ],
    products: [
        .iOSApplication(
            name: "YetAnotherIVOD",
            targets: ["YetAnotherIVOD"],
            bundleIdentifier: "com.yunlincla.YetAnotherIVOD",
            teamIdentifier: "JG35V2F68L",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft
            ],
            capabilities: [
                .outgoingNetworkConnections()
            ],
            appCategory: .video
        )
    ],
    dependencies: [
        .package(url: "https://github.com/Yunlincla/LYFetcher", .branch("main"))
    ],
    targets: [
        .executableTarget(
            name: "YetAnotherIVOD",
            dependencies: [
                .product(name: "LYFetcher", package: "lyfetcher")
            ],
            path: "./YetAnotherIVOD",
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals")
            ]
        )
    ]
)
